hosts:
  -
    name: victoria
    protocol: "http:"
    hostname: "localhost"
    port: 3031
    descriptor_uri: "/apis"
    format: "su-apiserver"
  -
    name: northern
    protocol: "http:"
    hostname: "localhost"
    port: 3031
    descriptor_uri: "/apis"
    format: "su-apiserver"
batch:
  all:
    victoria:
      bus: "bus-get"
      train: "train-get"
      train_delay: "train-delay"
  get_only:
    victoria:
      bus: "bus-get"
      train: "train-get"
  delay_only:
    northern:
      train_delay: "train-delay"
debug: false
app:
  port: 3031
  session:
    cleanup_time: 7200000
    cleanup_interval: 3600000
  global_request_timeout: 400000
  global_session_timeout: 3600000
log:
  customlevels:
    ERROR: 1
    INFO: 1
    LOG: 1
    WARN: 1
  path: "logs"
apis:
  base: "/apis"
  releases:
    stable: "v0.1.0"
    beta: "v1.0.0"
  health: "/service/healthcheck"
